flags: {}
packages:
- 'server'
extra-deps:
- purescript-bridge-0.10.1.0
- wai-websockets-3.0.1.1
- websockets-0.10.0.0
- servant-subscriber-0.6.0.0
- servant-purescript-0.7.0.0
resolver: lts-8.5
docker:
  enable: false
  require-docker-version: "> 17.0"
image:
  containers:
    - name: elblog
      base: fpco/stack-run
      add:
        blog: /blog
        static/dist/: /static/dist/
      entrypoints:
      - elblog-server